### ISSUE TITLE
typeFromIso

### ISSUE THREAD

**Issue by sledorze** [gcanti/io-ts-types#11]
Not sur about the naming, would something like that be ok?

```typescript
export const typeFromIso = <I, O>(iso: Iso<I, O>, is: (x: O) => x is O,  name: string): t.Type<I, O> =>
  new t.Type<I, O>(name, is, (s, _) => t.success(iso.to(s)), iso.from)
```

**Comment by gcanti** [comment]
isn't this already covered by https://github.com/gcanti/io-ts-types/blob/0da48194c599203249f1d2c0efbe925055d7c94e/src/monocle-ts/TypePrismIso.ts#L8?

**Comment by sledorze** [comment]
@gcanti when you have an `Iso` and don't want to go through a `Prism` to get the Type.
so for minimalism, no need.
for ease of use, (and less memory/cpu), desirable.
