### ISSUE TITLE
nanoid

### ISSUE THREAD

**Issue by steida** [gcanti/io-ts-types#121]
## 🚀 Feature request

I suppose [nanoid](https://github.com/ai/nanoid) is the state of art of client id generation.

**Comment by gcanti** [comment]
@steida not sure what are you requesting?

**Comment by DenisFrezzato** [comment]
I guess he's asking for a `nanoid` branded type, as there is one for `UUID`.

**Comment by gcanti** [comment]
@DenisFrezzato looks like nanoid is a generation tool, not a validator, how is relevant to this library?

**Comment by DenisFrezzato** [comment]
`nanoid` is an ID generation tool, as `UUID` is, so I'm guessing he's asking for a codec for `nanoid` IDs, like there is one for `UUID`.

**Comment by steida** [comment]
NanoID branded type plus smart constructor example with recommended usage for beginners, maybe.

```ts
interface NanoIDBrand {
  readonly NanoID: unique symbol;
}
export const NanoID = t.brand(
  t.string,
  (s): s is t.Branded<string, NanoIDBrand> => s.length <= 21, // regex would be better
  'NanoID',
);
export type NanoID = t.TypeOf<typeof NanoID>;
```

```ts
import nanoid from 'nanoid';
import { NanoID } from '../types';

export const createNanoID = () => NanoID.decode(nanoid());
```
