### ISSUE TITLE
t.stringFromRegex

### ISSUE THREAD

**Issue by waynevanson** [gcanti/io-ts-types#131]
### Current Behavior

Feature does not exist.

### Desired Behavior
User to use a `RegExp` to assert a `string`.

### Suggested Solution

First time I've written one of these.
Not tested.

```ts
import * as t from "io-ts";
import { pipe } from "fp-ts/lib/pipeable";
import { option as O, either as E } from "fp-ts";

const guardStringFromRegex = (regex: RegExp) => (a: unknown): a is string =>
  pipe(
    a,
    O.fromPredicate(t.string.is),
    O.map((a) => a.match(regex)),
    O.chain(O.fromNullable),
    O.isSome
  );

const stringFromRegex = (regexp: RegExp, name: string = "stringFromRegexp") => {
  const refinement = guardStringFromRegex(regexp);
  return new t.Type(
    name,
    refinement,
    (u, c) => (!refinement(u) ? t.failure(u, c) : t.success(u)),
    (a) => a
  );
};
```

### Who does this impact? Who is this for?

All users

### Describe alternatives you've considered

No alternatives. Tried looking around but didn't see anything.

### Your environment

| Software    | Version(s) |
| ----------- | ---------- |
| fp-ts       |      ^2.6.6      |
| io-ts       |      ^2.2.6      |
| io-ts-types |         ^0.3.4   |
| TypeScript  |      ^3.9.5      |

**Comment by mlegenhausen** [comment]
This looks a lot like what [fromRefinement](https://github.com/gcanti/io-ts-types/blob/master/src/fromRefinement.ts) is doing. You would use it like this

```ts
fromRefinement('MyRegExpType', (u): u is string => t.string.is(u) && /test/.test(u))
```

Or what I would recommend when you have strings that follow a certain structure is to use a [branded type](https://github.com/gcanti/io-ts/blob/master/index.md#branded-types--refinements)

**Comment by waynevanson** [comment]
@mlegenhausen 
That does look similar. I feel like the DX of the suggested solution for RegExp's are a better.

I didn't get that far in the documentation, so thank you for the references.

**Comment by EricCrosson** [comment]
May we close this issue @waynevanson ?
