### ISSUE TITLE
How to encode a blank string to null or undefined?

### ISSUE THREAD

**Issue by efenderbosch** [gcanti/io-ts-types#145]
Is there a simple extension, or do I need a completely new type?

**Comment by mlegenhausen** [comment]
What `Type` do you want to express? If you want something like `Type<Option<NonEmptyString>, string | null>` you could do `optionFromNullable(nonEmptyString)`.

**Comment by efenderbosch** [comment]
I want to avoid form submission that ends up with JSON like:

```json
{
  "foo": "someValue",
  "bar": ""
}
```
being sent to the server.

What should be sent instead is:
```json
{
  "foo": "someValue"
}
```

Server-side validation is enforcing an if-present-must-not-be-blank rule. However, simply tabbing through the input on the form and hitting submit is sending the empty string.

Right now I have a few custom "types", including:

```TypeScript
export const nullAsUndefined = fromNullable(iots.undefined, undefined)
export const OptionalString = iots.union([iots.string, nullAsUndefined])
```

Many of my "strings" on the models are ``OptionalString`` since I want deserialization of a missing attribute to be ``undefined`` instead of ``null``.

**Comment by efenderbosch** [comment]
I need the empty string -> undefined for POST, but I also need empty string -> null for PATCH.


Pretty standard entity like this:

```kotlin
export const Foo = iots.interface({
  id: UUID,
  name: iots.string,
  description: iots.union([iots.string, iots.undefined]),
  created: DateFromISOString,
  updated: DateFromISOString
})
export type Foo = iots.TypeOf<typeof Foo>

export interface FooPatch {
  name?: string;
  description?: string;
}

export const toFooPatch = (current: Foo, toUpdate: Foo): FooPatch => ({
  name: current.name === toUpdate.name ? undefined : toUpdate.name,
  description: current.description === toUpdate.description ? undefined : toUpdate.description
})
```

The JSON PATCH for an empty string for description from the UI should result look like: 

```json
{
  "description": null
}
```
instead of:
```json
{
  "description": ""
}
```

**Comment by efenderbosch** [comment]
I think ``mapToOutput`` is what I want. First pass, this looks like it is working how I want:

```kotlin
const emptyStringToUndefined = (s?: string): string | undefined => s?.trim()?.length === 0 ? undefined : s
const emptyStringToNull = (s?: string): string | null | undefined =>
  s === undefined ? undefined : s?.trim()?.length === 0 ? null : s

export const EmptyStringAsUndefined = mapOutput(iots.string, emptyStringToUndefined)
export type EmptyStringAsUndefined = iots.TypeOf<typeof EmptyStringAsUndefined>
export const EmptyStringAsNull = mapOutput(iots.string, emptyStringToNull)
export type EmptyStringAsNull = iots.TypeOf<typeof EmptyStringAsNull>
```
