### ISSUE TITLE
import(".../io-ts/lib/index").Decoder is not assignable to type import(".../io-ts/lib/Decoder").Decoder

### ISSUE THREAD

**Issue by ingun37** [gcanti/io-ts-types#149]
### Current Behavior

When I do
```typescript
import * as iots from "io-ts";
import * as D from "io-ts/Decoder";
import { withFallback } from "io-ts-types/lib/withFallback";
const MaterialInfo = D.type({
  mapElement: D.type({
    uiID: withFallback(iots.number, -1).asDecoder()
  }),
...
```

I get Error

>Type 'import("/Users/ingunjon/Desktop/ws/viewer/meshFactoryTS/node_modules/io-ts/lib/index").Decoder<unknown, number>' is not assignable to type 'import("/Users/ingunjon/Desktop/ws/viewer/meshFactoryTS/node_modules/io-ts/lib/Decoder").Decoder<unknown, number>'

### Expected behavior

I expect *Decoder* from `io-ts/lib/index` and *Decoder* from `io-ts/lib/Decoder` to not conflict each other.

### Your environment

Which versions of io-ts-types are affected by this issue? Did this work in previous versions of io-ts-types?

| Software    | Version(s) |
| ----------- | ---------- |
| fp-ts       |       2.9.3     |
| io-ts       |      2.2.13      |
| io-ts-types |      0.5.12      |
| TypeScript  |      4.0.3      |

**Comment by cdimitroulas** [comment]
Is there a workaround for this?

**Comment by ljani** [comment]
> Is there a workaround for this?

`io-ts-types` is using [the old `Decoder` interface](https://github.com/gcanti/io-ts/blob/2.2.13/src/index.ts#L106). If you want to use [the experimental `Decoder` interface](https://github.com/gcanti/io-ts/blob/2.2.13/src/Decoder.ts#L78), you need to implement most of (all of?) `io-ts-types` yourself, or switch back to the old interface.

**Comment by ljani** [comment]
> Is there a workaround for this?

`io-ts-types` [is using](https://github.com/gcanti/io-ts-types/blob/b9b773a37fe499124ea53354dc9d570da0bd20a0/src/withFallback.ts#L23) [the old Decoder interface](https://github.com/gcanti/io-ts/blob/2881d940b34fa7803e586262520b0c0795329287/src/index.ts#L106-L109) (exported from `io-ts/index.ts`). If you want to use [the new, experimental Decoder interface](https://github.com/gcanti/io-ts/blob/2881d940b34fa7803e586262520b0c0795329287/src/Decoder.ts#L78) (exported from `io-ts/Decoder.ts`, you need to implement most of (all of?) `io-ts-types` yourself, or switch back to using the old interface.

**Comment by gcanti** [comment]
you could define an adapter, here's a (simplistic) solution

```ts
import * as t from 'io-ts'
import * as D from 'io-ts/Decoder'
import { pipe } from 'fp-ts/function'
import * as E from 'fp-ts/Either'

export function toDecoder<A, O, I>(type: t.Type<A, O, I>): D.Decoder<I, A> {
  const decode = type.decode.bind(type)
  return {
    decode: (i) =>
      pipe(
        decode(i),
        E.mapLeft(() => D.error(i, type.name))
      )
  }
}

import { withFallback } from 'io-ts-types/withFallback'

export const MaterialInfo = D.type({
  mapElement: D.type({
    uiID: toDecoder(withFallback(t.number, -1))
  })
})
```
