### ISSUE TITLE
Base64 decode/encode

### ISSUE THREAD

**Issue by piu130** [gcanti/io-ts-types#155]
### Desired Behavior

Would be cool, if this library supports base64 decode and encode natively.
My scenario: I fetch some base64 encoded Json `StringFromBase64.pipe(JsonFromString)`.

### Suggested Solution

I'm new to io-ts, so this might not be the correct way to implement it:

```ts
export const StringFromBase64 = new t.Type<string, string, string>(
    'StringFromBase64',
    (u): u is string => typeof u === 'string',
    (s, c) => {
        try {
            return t.success(atob(s));
        } catch (e) {
            return t.failure(s, c);
        }
    },
    s => btoa(s)
);
```

**Comment by piu130** [comment]
There is no `atob` and `btoa` in NodeJS.

**Comment by DenisFrezzato** [comment]
@piu130 there isn't, but the same can be achieved using `Buffer` and character encoding, see [this](https://nodejs.org/api/buffer.html#buffer_buffers_and_character_encodings).
