### ISSUE TITLE
Support NonEmptyArray Type from fp-ts

### ISSUE THREAD

**Issue by sledorze** [gcanti/io-ts-types#18]
I propose to implement it base don your proposal @gcanti 
https://github.com/gcanti/io-ts/issues/132

**Comment by gcanti** [comment]
My quick implementation there is ok? Would you like to send a PR?

**Comment by sledorze** [comment]
@gcanti there was a little error in the types :)

**Comment by gcanti** [comment]
Ah you are right, so why does it type check??

**Comment by sledorze** [comment]
because `t.Mixed` extends `t.Type<any, any, t.mixed>` I guess

**Comment by sledorze** [comment]
maybe that's better

```typescript
export const createNonEmptyArrayFromArray = <A, O = A>(
  type: t.Type<A, O, t.mixed>
): t.Type<NonEmptyArray<A>, O[], t.mixed> =>
  t.array(type).pipe(getNonEmptyArrayFromArray(), `NonEmptyArray<${type.name}>`)
```

**Comment by sledorze** [comment]
That way it no more fails.
(I know that's deceptive :/ )

**Comment by sledorze** [comment]
Also simply removing type annotation infers the right type.

```typescript

export const createNonEmptyArrayFromArray = <RT extends t.Type<any, any, t.mixed>
>(
  type: RT
) =>
  t.array(type).pipe(getNonEmptyArrayFromArray<t.TypeOf<RT>>(), `NonEmptyArray<${type.name}>`)

```

**Comment by gcanti** [comment]
> because t.Mixed extends t.Type<any, any, t.mixed> I guess

If true, that's bad... 
Let me investigate

**Comment by sledorze** [comment]
I share your concerns, I also use that pattern extensively :(

**Comment by gcanti** [comment]
So my guess is that here

```ts
export const nonEmptyArray = <RT extends t.Mixed>(type: RT): t.Type<t.TypeOf<RT>, t.OutputOf<RT>, t.mixed> => {
  return t.array(type).pipe(getNonEmptyArrayFromArray(), `NonEmptyArray<${type.name}>`)
}
```

the type checker resolves eagerly `t.TypeOf<RT>` resulting in `any` while here

```ts
export const nonEmptyArray2 = <A, O>(type: t.Type<A, O, t.mixed>): t.Type<NonEmptyArray<A>, Array<O>, t.mixed> =>
  t.array(type).pipe(getNonEmptyArrayFromArray(), `NonEmptyArray<${type.name}>`)
```

you get the proper type checking. So the first pattern is safe for the consumer but unsafe for the developer who's writing the combinator. 

I must remember this and try to avoid the pattern `RT extends Mixed` as much as I can

**Comment by sledorze** [comment]
@gcanti it's really worst that I was imaginating.
After a long debugging session, I've stumbled on another case derived from the very same issue.

Imagine that you try to apply the second scheme; there's no way to add constraints to let's say A or O if t.Type was requiring it (because then you have variance issue on the return type).

That forces us to use the first, unsafe scheme, were the return type can we wrongly inferred (because of any) so that means only the caller can put the return type constraints at the call site (no more any would be inferred at this stage).

**Comment by gcanti** [comment]
> Imagine that you try to apply the second scheme; there's no way to add constraints to let's say A or O if t.Type was requiring it (because then you have variance issue on the return type).

Could you please show an example?

**Comment by sledorze** [comment]
@gcanti based on the feedback I received from the issue I've opened in Typescript repo, it looks like we may use this:
```typescript
export const createNonEmptyArrayFromArray = <T extends t.Type<A, O, t.mixed>, A = any, O = any>(
  type: T
): t.Type<NonEmptyArray<t.TypeOf<T>>, t.OutputOf<T>[], t.mixed> =>
  t.array(type).pipe(getNonEmptyArrayFromArray(), `NonEmptyArray<${type.name}>`)
```

Inference works, both for the end user and the lib writer.

The explanation is that:
- in the function, the compiler cannot infer to any as there's a type param that can be bound.
- out of the function, it correctly infers from the context, extracting the real types via the structure.

Beware, you should absolutely not do:

```typescript
export const createNonEmptyArrayFromArray = <T extends t.Type<A, O, t.mixed>, A = any, O = any>(
  type: T
): t.Type<NonEmptyArray<A>, O[], t.mixed> =>
  t.array(type).pipe(getNonEmptyArrayFromArray(), `NonEmptyArray<${type.name}>`)
```

as out of the function (if not provided), the A and O type param resolve to any, so the return type will also infer it's signature based on any; `t.Type<NonEmptyArray<any>, any[], t.mixed>`.

I think we have a scheme that works.

What do you think?

**Comment by gcanti** [comment]
What's the advantage of

```ts
export const createNonEmptyArrayFromArray = <T extends t.Type<A, O, t.mixed>, A = any, O = any>(
  type: T
): t.Type<NonEmptyArray<t.TypeOf<T>>, t.OutputOf<T>[], t.mixed> =>
  t.array(type).pipe(getNonEmptyArrayFromArray(), `NonEmptyArray<${type.name}>`)
```

over

```ts
export const createNonEmptyArrayFromArray = <A, O>(
  type: t.Type<A, O, t.mixed>
): t.Type<NonEmptyArray<A>, Array<O>, t.mixed> =>
  t.array(type).pipe(getNonEmptyArrayFromArray(), `NonEmptyArray<${type.name}>`)
```

?

**Comment by sledorze** [comment]
If the end user has to provide those types explicitly the UX is different.

There's no advantages to it, there're both typesafe (provided the lib author do not use A and O directly in the return type which in fact may be a shortcoming of the first solution).

Note the it maps to different types which may be useful in some contexte; for instance if you would return a type projection that's not part of the function type parameters and is dependent of the actual T type; in that case the second solution is not applicable.
