### ISSUE TITLE
After switching to 0.3.3 importing is not working

### ISSUE THREAD

**Issue by kbiedrzycki** [gcanti/io-ts-types#34]
When trying to switch to version with tagged custom types, now I can't use modules, compiler is giving error:
```
error TS4023: Exported variable 'xxx' has or is using name 'DateFromISOStringType' from external module "project/node_modules/io-ts-types/lib/Date/DateFromISOString" but cannot be named.
```

**Comment by gcanti** [comment]
@kbiedrzycki This is a TypeScript gotcha:

https://github.com/Microsoft/TypeScript/issues/9944

Basically you always need to import any type which will end up appearing in your declaration file, whether you use it explicitly in your code or not.

Alternatively adding a type annotation makes the error go away: [example](https://github.com/gcanti/io-ts-types/blob/067423fe3b26a7366e11b3df9e6eb6f62c6d7e9e/src/number/IntegerFromString.ts#L4)

**Comment by kbiedrzycki** [comment]
Okay, that makes sense, issue resolved then, that worked.
