### ISSUE TITLE
Validating a previously-validated type (OptionFromNullable)

### ISSUE THREAD

**Issue by dotbear** [gcanti/io-ts-types#36]
Say I have the following:
```ts
const MyType = t.interface({
  foo: option(t.string),
});

const myObject = {
  foo: "bar",
}
```
And I then run `t.validate(myObject, MyType);`. The resulting object will be something to the effect of `{ foo: { _tag: "Some", value: "bar" } }`. If I now decide to try and validate it once more against the same type: `t.validate({ foo: { _tag: "Some", value: "bar" } }, MyType);`, validation will fail because the value isn't `string | null | undefined`.

Is there a specific reason why `OptionFromNullable` doesn't have something like
```ts
(s, c) => is(u) ? t.success(u) : (Nullable.validate(s, c).chain(u => t.success(fromNullable(u))))
```
where `is` is the normal `OptionFromNullable.is` function, but extracted to scope.

We're running some lengthy validation chains and sometimes validate our objects twice and this is causing us a bit of pain where we have to first `cloneToPlainObject` to unwrap the options before revalidating.

Thoughts? :)

**Comment by sledorze** [comment]
@dotbear `validate` is not idempotent; indeed it also provides conversion.
What you're experiencing is completely normal (and desirable).

It looks like you're loosing your object types and that's why you want to (re)validate (decode) them.
That's where you should act IMHO.

P.S.: If you want you may create a combinator which does what you propose but that can not be the default behaviour of io-ts.

**Comment by leemhenson** [comment]
It seems like you are saying you believe this is ok:

```ts

const Foo = t.interface({
  name: createOptionFromNullable(t.string),
});

type Foo = t.TypeOf<typeof Foo>;

const noneFoo: Foo = {
  name: none,
};

t.validate(noneFoo, Foo) // <- fails
```

That seems a little counter-intuitive to me.

**Comment by sledorze** [comment]
Validate naming may be counter intuitive indeed.
Think 'decode' (which it uses under the hood).
Also in that specific use case 'is' is intuitive.
I think you want 'validate' to be either one or the other depending on the actual value.

**Comment by leemhenson** [comment]
Yes, that makes sense. As long as `is` is doing all the right checks (does the literal match, is the number in the expected range etc), then maybe what the OP wants is: 

```ts
const isFoo = either.fromPredicate(Foo.is, () => undefined);
isFoo(noneFoo).alt(t.validate(noneFoo, Foo))
```

I agree perhaps the name `validate` could be better.

**Comment by sledorze** [comment]
Yes 'is' is accurate
