### ISSUE TITLE
Compilation problems using optional types

### ISSUE THREAD

**Issue by nikcorg** [gcanti/io-ts-types#38]
I'm feeling a bit baffled, after having successfully used this project and the related ones at work for what seems like a long time, I'm now struggling to get started with a teeny weeny side-project of mine. We've been holding off upgrading to the latest versions at work, but knowing that's looming just around the corner I started my own experiment with all the latest versions of fp-ts, io-ts et al. in order to familiarise myself with the changes.

The project has basically two types: 

```
export const Entry = t.interface({
  related: OptionalArrayOfRelatedEntry,
  source: OptionalUrlString,
  title: NonEmptyString,
  unread: t.boolean,
  url: UrlString,
});
```
([source here](https://github.com/nikcorg/tldr/blob/feature/toolify/src/types/Entry.ts))

and 

```
export const Archive = t.interface({
  entries: ArrayOfEntry,
  title: NonEmptyString,
});
```
([source here](https://github.com/nikcorg/tldr/blob/feature/toolify/src/types/Archive.ts))

I'm using `createOptionFromNullable` to create the Optional types, their definitions are:

- [`OptionalArrayOfRelatedEntry = Option<Array<UrlString | { title: NonEmptyString, url: UrlString }>>`](
https://github.com/nikcorg/tldr/blob/feature/toolify/src/types/Entry.ts#L20-L21)
- [`OptionalUrlString = Option<UrlString>`](https://github.com/nikcorg/tldr/blob/feature/toolify/src/types/strings.ts#L26-L27)

I'm suspecting there must be some PEBKAC here, but I can't find it. What happens is when I try and compile the code I just get a TS sad-face regarding the optional types (look here for full sadness: https://pastebin.com/xeCNtgW2) which I can't make sense out of.

When the optional types in `Entry` are commented out, the code compiles fine. However, hovering the types in VSCode (at point of definition) gives no hint of any problem (type hints look correct, albeit somewhat repetitive [can it be a recursion issue?]) and no red underlines are drawn. 

Hovering the `Archive` type where it's [used as an imported type](https://github.com/nikcorg/tldr/blob/feature/toolify/src/index.ts#L50) shows a huge TS sad-face (see here https://pastebin.com/b3jAGsFY)

Any idea what could be the problem?

Here's some package versions which might be relevant

```
├── fp-ts@1.3.0
├─┬ io-ts@1.0.5
│ └── fp-ts@1.3.0  deduped
├─┬ io-ts-reporters@0.0.20
│ ├── fp-ts@1.3.0  deduped
│ └── io-ts@1.0.5  deduped
├─┬ io-ts-types@0.3.4
│ ├── fp-ts@1.3.0  deduped
│ ├── io-ts@1.0.5  deduped
│ ├─┬ monocle-ts@1.0.0
│ │ └── fp-ts@1.3.0  deduped
│ └── newtype-ts@0.2.0  deduped
├─┬ newtype-ts@0.2.0
│ └── fp-ts@1.3.0  deduped
├── ts-node@6.0.0
└── typescript@2.8.3
```

**Comment by gcanti** [comment]
@nikcorg thanks for the detailed report. The issue seems related to `safeloadYaml.ts`

```diff
-export const safeloadYaml = <A>(type: t.Type<any, A>) => (
+export const safeloadYaml = <A, O>(type: t.Type<A, O>) => (  
```

Explanation:

In `io-ts@1.x.x` there are 3 type parameters

```
Type<A, O = A, I = mixed>
```

while in `io-ts@'.9.x` there are only 2 type parameters

```
Type<S, A>
```

So `S` (the input type) become `I` and goes in last position, after `O` (the output type).

Note. `type` here

```ts
export const safeloadYaml = <A, O>(type: t.Type<A, O>) => (  
```

must also be polymophic in `O` (other than in `A`), otherwise by default `O = A` and that's not true in the case of `createOptionFromNullable`

**Comment by nikcorg** [comment]
Many thanks. That has indeed solved the issue. 

I did begin to suspect that the problem was indeed in `safeloadYaml` after opening the issue last night, but I still couldn't fix it.
