### ISSUE TITLE
NumberFromString validates '2a' as a number (2)

### ISSUE THREAD

**Issue by sledorze** [gcanti/io-ts-types#40]
This is due to `parseFloat` behaviour

**Comment by sledorze** [comment]
Note that:
Number("2") === 2
Number("2a") === Nan
Number("2.4") === 2.4
Number("2,4") === Nan

**Comment by sledorze** [comment]
Also jsperf seems indicates that doing:

x*1 behaves the same as Number(x) but way faster:

https://jsperf.com/number-vs-plus-vs-toint-vs-tofloat/32

**Comment by gcanti** [comment]
Fixed by https://github.com/gcanti/io-ts-types/pull/41
