### ISSUE TITLE
/Users/giulio import?

### ISSUE THREAD

**Issue by AlexMouton** [gcanti/io-ts-types#46]
import("../../../../../../../../Users/giulio/Documents/Projects/github/io-ts-types/node_modules/newtype-ts") 

Hi
Just wondering if you meant to leave this reference this way?

Thanks
Alex

**Comment by gcanti** [comment]
Thanks for reporting, I'm afraid is an evil side effect of the new `import()` types 

https://blogs.msdn.microsoft.com/typescript/2018/05/31/announcing-typescript-2-9/

Before ts 2.9 there would be an error, namely the dreaded "Exported variable 'X' has or is using name 'Y' from external module 'a/file/path' but cannot be named", now it just emit wrong declarations

**Comment by gcanti** [comment]
Fix released

**Comment by sledorze** [comment]
We're fighting the same hard Issue in our monorepo context, it impacts all projects with declaration in such a way we had to automatise/detect these imports as a prepush hook.
All exported valus must have well named exported types directly as this fix demonstrate or by exporting the whole module name (which breaks code elimination via tools like webpack and such).

**Comment by agos** [comment]
This is possibly related to these TS issues:
- https://github.com/Microsoft/TypeScript/issues/25279
- https://github.com/Microsoft/TypeScript/issues/25769
- https://github.com/Microsoft/vscode/issues/53597
- https://github.com/Microsoft/TypeScript/issues/24599
