### ISSUE TITLE
add fallback combinator

### ISSUE THREAD

**Issue by sledorze** [gcanti/io-ts-types#49]
We've just had the need for some default value as part of a decoding (long story, short; firebase erase empty dictionaries..).
(We have tests)

```typescript
export const withDefault = <T, O>(Type: t.Type<T, O>, v: T): typeof Type =>
  t.union([
    Type,
    new t.Type(`withDefault${Type.name}`, Type.is, (_i, _context) => right(v), Type.encode)
  ])
```

Usage:
```typescript
const Type = withDefault(
  t.dictionary(t.string, ActionPayloadData),
  {}
)

// use Type as usual
```

I'm not sure about the naming (both the function and the Type name) do you have some better one?

**Comment by sledorze** [comment]
I though I could break it into a `succeed` and `withDefault` but that would requiers a Setoid for succeed, which brings additional constraints.
That made me think that a default on a refinement is also problematic, what would be the definition of `is` then?
I'm going back to think we must provide a Setoid.

```typescript
export const succeed = <T, O>(Type: t.Type<T, O>, setoid: Setoid<T>, v: T): typeof Type =>
  new t.Type(`succeed${Type.name}`, (m: t.mixed) : m is T => Type.is(m) || setoid.equals(v, m), (_i, _context) => right(v), Type.encode)
```

But I think I can't reasonably call the 'Setoid' equals with a `mixed` (unknown) value.

So maybe in the End I may only be able to define the `Decode` interface.


The only valid thing would then be to construct a withDefault which validates the default value is part of the domain; that would work but being very impractical.

So I guess the best is to do that:

```typescript
export const succeed = <T, O>(Type: t.Type<T, O>, setOid: Setoid<T>, v: T): typeof Type => {
  const isValid = Type.decode(v).isRight()
  return new t.Type(
    `succeed${Type.name}`,
    (m: t.mixed): m is T => isValid && Type.is(m) &&  setOid.equals(m, v),
    (_i, _context) => Type.validate(v, _context),
    _ => Type.encode(v)
  )
}

export const withDefault = <T, O>(Type: t.Type<T, O>, setOid: Setoid<T>, v: T) =>
  t.union([Type, succeed(Type, setOid, v)], `withDefault${Type.name}`)
```

That seems correct but having to pass the `setoid` imposes a lot of constraints.. (it's not like we have implicits)
@gcanti what do you think about it?

**Comment by sledorze** [comment]
All in all `succeed` may be useful but imposes too much to `withDefault`.

Let's keep things simple:

```typescript
export const withDefault = <A, O, I>(Type: t.Type<A, O, I>, v: I) =>
  new t.Type<A, O, I>(
    `withDefault(${Type.name})`,
    Type.is,
    (i, context) => {
      const typeValid = Type.validate(i, context)
      return typeValid.isRight() ? typeValid : Type.validate(v, context)
    }, // we must revalidate for the context.
    Type.encode
  )
```

(I realised what we really do is doing a substitution of the input in case of non match).

@gcanti agree with it?

**Comment by gcanti** [comment]
> I realised what we really do is doing a substitution of the input in case of non match

This behaviour doesn't align well with the name of the combinator, a "default" should be applied before validation and if the input is "missing", i.e. when is `undefined`

```ts
const T = withDefault(t.type({ foo: t.string }), { foo: 'bar' })

console.log(T.decode({ foo: 1 })) // <= this should be a left but outputs a right({"foo": "bar"})
```

I would try to respect the usual semantic associated with the term "default" in JavaScript

```ts
export const withDefault = <A, O, I>(Type: t.Type<A, O, I>, v: I) =>
  new t.Type<A, O, I>(`withDefault(${Type.name})`, Type.is, (i = v, context) => Type.validate(i, context), Type.encode)
```

Alas, since most of the runtime types have `mixed` as `I`, it looks like is easy to pass a wrong value for the argument `v`

```ts
const T = withDefault(t.type({ foo: t.string }), 'wat')
```

**Comment by sledorze** [comment]
@gcanti I agree the naming is misleading.
Maybe `fallback` ?

As for passing the wrong type as a parameter; that would be silent at compile time but would correctly behave at runtime (as its revalidated).

However you're right, that's great feedback!
(I had to add an additional constraint between I and O)

```typescript
export const fallback = <A, O extends I, I>(Type: t.Type<A, O, I>, v: A) => {
  const vi = Type.encode(v)
  return new t.Type<A, O, I>(
    `withDefault(${Type.name})`,
    Type.is,
    (i, context) => {
      const typeValid = Type.validate(i, context)
      return typeValid.isRight() ? typeValid : Type.validate(vi, context)
    }, // we must revalidate for the context.
    Type.encode
  )
}
```

**Comment by gcanti** [comment]
`fallback` looks good

If the fallback `v` has type `A` I think that there's no need to re-validate, you can just return `success(v)`. AFAIK the only unsafe exception would be a refinement but we could special case that by sniffing the `Type` argument.

**Comment by sledorze** [comment]
@gcanti that was my concern, we don't know what Type came before (could be user defined any Type), that would defeat the sniffing approach.

So I'm afraid for the sake of consistency, we can't really bypass that revalidation.

**Comment by gcanti** [comment]
I see, it's quite inefficient though. What about?

```ts
export const fallback = <A, O, I>(type: t.Type<A, O, I>, a: A) => {
  const isFallbackValid = type.is(a)
  return new t.Type<A, O, I>(
    `fallback(${type.name})`,
    type.is,
    (i, context) => {
      const validation = type.validate(i, context)
      return validation.isLeft() && isFallbackValid ? t.success(a) : validation
    },
    type.encode
  )
}
```

**Comment by sledorze** [comment]
@gcanti Ok,

Here we would not find out that the fallback is actually invalid from the error BUT if there's an error, that's clearly because the fallback is invalid.
I'm ponderating is that would be acceptable.

Another possibility is to be (very) slow when the fallback is invalid (so should only be visible in dev):
```typescript
export const fallback = <A, O extends I, I>(type: t.Type<A, O, I>, a: A) => {
  const isFallbackValid = type.is(a)
  return new t.Type<A, O, I>(
    `fallback(${type.name})`,
    type.is,
    (i, context) => {
      const validation = type.validate(i, context)
      return validation.isRight()
        ? validation
        : isFallbackValid
          ? t.success(a)
          : type.validate(type.encode(a), context)
    },
    type.encode
  )
}
```

At this point, I'm really happy with both; @gcanti your decision?.

**Comment by gcanti** [comment]
I'm fine with yours too. In the end I'd go for mine since there's no `O extends I` constraint

**Comment by sledorze** [comment]
@gcanti great; I'll make a PR soon (after my duties)

**Comment by gcanti** [comment]
Ok, thanks. We could also add the usual optional `name` argument

```ts
export const fallback = <A, O, I>(type: t.Type<A, O, I>, a: A, name: string = `fallback(${type.name})`) => {
  const isFallbackValid = type.is(a)
  return new t.Type<A, O, I>(
    name,
    type.is,
    (i, context) => {
      const validation = type.validate(i, context)
      return validation.isLeft() && isFallbackValid ? t.success(a) : validation
    },
    type.encode
  )
}
```

**Comment by gcanti** [comment]
Looks like TypeScript is not able to infer the correct type here

```ts
const dic = t.dictionary(t.string, t.number)
//                 v--- :(
// const T: t.Type<{}, t.OutputOfDictionary<t.StringType, t.NumberType>, t.mixed>
const T = fallback(dic, {})
```

Changing the signature like this makes it work

```ts
export const fallback = <T extends t.Any>(
  type: T,
  a: t.TypeOf<T>,
  name: string = `fallback(${type.name})`
): t.Type<t.TypeOf<T>, t.OutputOf<T>, t.InputOf<T>> => {
  const isFallbackValid = type.is(a)
  return new t.Type(
    name,
    type.is,
    (i, context) => {
      const validation = type.validate(i, context)
      return validation.isLeft() && isFallbackValid ? t.success(a) : validation
    },
    type.encode
  )
}
```

**Comment by gcanti** [comment]
Alternatively (I'm not keen on changing the signature) you can provide an explicit type annotation for the fallback value in this particular case

```ts
const dict = t.dictionary(t.string, t.number)
type Dict = t.TypeOf<typeof dict>
const defaultValue: Dict = {}
const T = fallback(dict, defaultValue)
// OK:
// const T: t.Type<t.TypeOfDictionary<t.StringType, t.NumberType>, t.OutputOfDictionary<t.StringType, t.NumberType>, t.mixed>
```

**Comment by sledorze** [comment]
Currying to the rescue:

```typescript
export const fallback = <A, O, I>(type: t.Type<A, O, I>) => (a: A, name = `fallback(${type.name})`) => {
  const isFallbackValid = type.is(a)
  return new t.Type<A, O, I>(
    name,
    type.is,
    (i, context) => {
      const validation = type.validate(i, context)
      return validation.isLeft() && isFallbackValid ? t.success(a) : validation
    },
    type.encode
  )
}
```

Usage:

```typescript
const dic = t.dictionary(t.string, t.number)
const T = fallback(dic)({}) // Type: T: t.Type<t.TypeOfDictionary<t.StringType, t.NumberType>, t.OutputOfDictionary<t.StringType, t.NumberType>, t.mixed>
```

@gcanti I would like to favor that solution (easier to use), ok?

**Comment by gcanti** [comment]
Agreed
