### ISSUE TITLE
Maintaining backward compatibility with types - mapType?

### ISSUE THREAD

**Issue by OfirArviv** [gcanti/io-ts-types#64]
Hi, 
I run into the problem of maintaining backward compatibility when changing the type / decoder, came with a solution and wanted to ask what you think and if there is a best practice?
Examples of the scenarios can be:

- The contract was defined with a property name which was misspelled and we want the correct it. The problem arise - how can we do it while maintaining backward-compatibility? If we just change the property name in the dynamic type all previously instance of the data will not pass validation.

- Similar - Sometimes we introduce new properties in our contract and deprecated old ones, and using fallback or subset of the contract is not good enough to maintain backward-compatibility  (we may want to transform some deprecated values into new properties using a custom logic),

I tried to create a function that is similar to the _mapOutput_ function
```
const mapType = <A, O, I, A_tag, O_tag, I_tag>(type_1: t.Type<A, O, I>, 
                                        type_2: t.Type<A_tag, O_tag, I_tag>,
                                        f: (a: A) => A_tag,
                                        name?: string)
                                        : t.Type<A_tag, O,_tag I> =>
    new t.Type(
        name === undefined ? `${type_1.name}=>${type_2.name}` : name,
        type_2.is,
        (i, c) => type_1.validate(i,c).map(val => f(val)),
        a => type_2.encode(a)
```

A simple example will be:
```
const PersonDynamicType = t.type({
    name: t.string,
    Age: t.number
},);

const PersonDynamicType_v2 = t.type({
    name: t.string,
    age: t.number,
});


const PersonDynamicType_v2_backward__comp_w_v1 =
    mapType(PersonDynamicType,
        PersonDynamicType_v2,
         v1 => { return { name: v1.name, age: v1.Age};},);
```
Is this the way to do it?
Thanks

**Comment by gcanti** [comment]
@OfirArviv looks good to me. Nitpick: `I_tag` looks useless.

```ts
const mapType = <A, O, I, B, P>(
  v1: t.Type<A, O, I>,
  v2: t.Type<B, P, I>,
  f: (a: A) => B,
  name?: string
): t.Type<B, P, I> =>
  new t.Type(name === undefined ? `${v1.name}=>${v2.name}` : name, v2.is, (i, c) => v1.validate(i, c).map(f), v2.encode)
```

You could even generalize `f` (let's say there are cases when the trasformation v1 -> v2 might fail)

```ts
const chainType = <A, O, I, B, P>(
  v1: t.Type<A, O, I>,
  v2: t.Type<B, P, I>,
  f: t.Validate<A, B>,
  name?: string
): t.Type<B, P, I> =>
  new t.Type(
    name === undefined ? `${v1.name}=>${v2.name}` : name,
    v2.is,
    (i, c) => v1.validate(i, c).chain(a => f(a, c)),
    v2.encode
  )

const PersonDynamicType = t.type({
  name: t.string,
  Age: t.union([t.number, t.undefined]) // <= optional in v1
})

const PersonDynamicType_v2 = t.type({
  name: t.string,
  age: t.number // <= required in v2
})

const PersonDynamicType_v2_backward__comp_w_v1 = chainType(PersonDynamicType, PersonDynamicType_v2, (v1, c) => {
  return v1.Age === undefined ? t.failure(v1, c) : t.success({ name: v1.name, age: v1.Age })
})

import { PathReporter } from 'io-ts/lib/PathReporter'
console.log(PathReporter.report(PersonDynamicType_v2_backward__comp_w_v1.decode({ name: 'foo' })))
// => [ 'Invalid value {"name":"foo"} supplied to : { name: string, Age: (number | undefined) }=>{ name: string, age: number }' ]
```

**Comment by OfirArviv** [comment]
Thanks for the reply and for the suggestions.
You are right - the I_tag is useless, I didn't realized it :) Also like the more generalized `f`.

Also, after further thinking about my scenarios I realized I probably need another function, because I don't really want to be aware what version of the payload I'm receiving, I just want to be able to handle them all.
I came up wit this:
```
export const fallbackDecoder = <A, O, I>(type: t.Type<A, O, I>) => (
    decoder: t.Decoder<I, A>,
    name = `${type.name} w/fallbackDecoder(${decoder.name})`,
  ): t.Type<A, O, I> => {
    return new t.Type<A, O, I>(
      name,
      type.is,
      (i, context) => {
        const validation = type.validate(i, context);
        const fallbackValidation =  decoder.validate(i, context);
        return validation.isLeft() && fallbackValidation.isRight() ? fallbackValidation : validation;
      },
      type.encode,
    );
};

```

With this I can also chain multiple fallback decoders in case there are multiple old version. I'm pondering if I want to chain the different validations errors in case the both validation fails.

Thanks again :)
