### ISSUE TITLE
OptionFromNullableType output type is any

### ISSUE THREAD

**Issue by OfirArviv** [gcanti/io-ts-types#67]
Hi,

I noticed that the output type of `OptionFromNullable` Type  is `any`. What is the rational for this?
For example if I have a runtime type
```
const status = t.type({
        lastViewed: createOptionFromNullable(DateFromISOString),
})
```
It implies that the contract I'm expecting is 
```
{
 lastViewed: string | null
}
```

But the output type, which in some sense symbolized that contract I'm suppose to send back (and normally also receive) , getting by 
```
type status_output= t.OutputOf<typeof status>;
```
will be:
```
{
 lastViewed: any
}
````

Thanks!

**Comment by gcanti** [comment]
@OfirArviv thanks for reporting, looks like an upstream bug: typescript is not able to infer the correct output type inside a `type` call, however if I define an intermediate runtime type (`X`) everything's fine

```ts
const X = createOptionFromNullable(t.string)

type XT = t.OutputOf<typeof X> // string | null (CORRECT)

const Y = t.type({
  lastViewed: createOptionFromNullable(t.string)
})

type YT = t.OutputOf<typeof Y.props.lastViewed> // any (WRONG)

const Z = t.type({
  lastViewed: X
})

type ZT = t.OutputOf<typeof Z.props.lastViewed> // string | null (CORRECT)
```
