### ISSUE TITLE
JSON name conflicts with lib.es6.d.ts

### ISSUE THREAD

**Issue by sledorze** [gcanti/io-ts-types#8]
As a matter to help with auto import and the like it would be better to have a non conflicting name.
Maybe `JSONType`?

https://github.com/gcanti/io-ts-types/blob/d62c0a28982a03a06414615754950804d2b09541/src/monocle-ts/StringJSONPrism.ts#L6

Also JSON is not exposed outside of the package and 'cannot be named'

**Comment by gcanti** [comment]
> Maybe `JSONType`?

ok

> Also JSON is not exposed outside of the package 

What do you mean? The `JSON` type is exported

> and 'cannot be named'

Found this https://github.com/Microsoft/TypeScript/issues/5711

**Comment by sledorze** [comment]
@gcanti yeah, I know one have to fully annotate the type for its types names to be exported correctly.
About JSON, it is annotated as export but not from here:
https://github.com/gcanti/io-ts-types/blob/master/src/index.ts#L10

so one has to do the heavy thing:
```typescript
import { JSON as JSONType } from 'io-ts-types/lib/JSON/JSONFromString'
```

**Comment by gcanti** [comment]
> About JSON, it is annotated as export but not from here

Ah! Sorry, I didn't realize that :)

**Comment by sledorze** [comment]
great!

**Comment by gcanti** [comment]
Fix released

**Comment by sledorze** [comment]
@gcanti  thanks a lot
