### ISSUE TITLE
Autogen lenses from interfaces?

### ISSUE THREAD

**Issue by dwhitney** [gcanti/io-ts-types#81]
Is there a script that will autogen lenses from a given typescript interface? I'd like to run a script that took a given typescript file as input and it output lenses for all of the interfaces in the given file. I can build it myself, but I thought I'd ask before doing so. Thanks

**Comment by gcanti** [comment]
@dwhitney no, there's a `lensesFromInterface.ts` helper but is based on `io-ts` codecs

**Comment by dwhitney** [comment]
I've got to have a `Codec` for that to work, right?

**Comment by gcanti** [comment]
Yes, see https://github.com/gcanti/io-ts-types#lensesfrominterface
