### ISSUE TITLE
withMessage helper does not work as expected

### ISSUE THREAD

**Issue by karthikiyengar** [gcanti/io-ts-types#95]
Versions:
```
"io-ts": "^1.8.5",
"io-ts-types": "^0.4.6",
```

Minimal reproduction:
```typescript
import { withMessage } from "io-ts-types/lib/withMessage";
import * as t from "io-ts";
import { PathReporter } from "io-ts/lib/PathReporter";

const T = withMessage(t.number, () => "Invalid number!");

const decoded = T.decode(null);
console.log(PathReporter.report(decoded));
//=> [ 'Invalid value null supplied to : number' ]
```

Looks like the message property is not being set correctly - reports as `undefined`

**Comment by karthikiyengar** [comment]
Did a bit of digging around, looks like this works.
```
const decoded = T.validate(null, t.getDefaultContext(T))
console.log(PathReporter.report(decoded))
```
Looks like issues with passing the context to decode?

**Comment by gcanti** [comment]
@karthikiyengar weird, your repro is literally the test I wrote [here](https://github.com/gcanti/io-ts-types/blob/36f6f2c393fd8fded2aeec1597b90be0f7f30d9b/test/withMessage.ts)

**Comment by gcanti** [comment]
Wait... I just updated my local version to `io-ts@1.8.5` and I can see the issue now. Let me investigate...

**Comment by gcanti** [comment]
@karthikiyengar just released a patch

**Comment by karthikiyengar** [comment]
Thanks a lot @gcanti, that was incredibly quick :-)

**Comment by gcanti** [comment]
Thanks to you for the bug report
